# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_courseorg_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='orgization/teacher/%Y/%m', verbose_name='教师头像'),
        ),
    ]
