"""
Django settings for jyteaches project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))  #将apps这个目录作为app的根目录
sys.path.insert(0,os.path.join(BASE_DIR,'extra_app'))  #导入xadmin


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tlo@1q=0ekv24-5!1%i=oj#g#v!w4rf@etxgp6w75l9u+r39rs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'courses',
    'operations',
    'organizations',
    'crispy_forms', #xadmin app注册
    'xadmin',
    'captcha', #验证码应用
    'pure_pagination', # 分页应用
]

AUTH_USER_MODEL = 'users.UserProfile' #覆盖django自带的表
AUTHENTICATION_BACKENDS = [
    'users.views.CustomBackend'
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',  # 注意位置，在后
]

ROOT_URLCONF = 'jyteaches.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,   #改成False后xadmin不能进入
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',   #引入media
            ],
        },
    },
]

WSGI_APPLICATION = 'jyteaches.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jyteach',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR,'static'),
# )
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/static')

STATICFILES_DIRS =[
    os.path.join(BASE_DIR,'static')
]

EMAIL_HOST = "smtp.sina.com" #[Errno 11001] getaddrinfo failed
EMAIL_PORT = 25
EMAIL_HOST_USER = 'smokerkiss@sina.com'
EMAIL_HOST_PASSWORD = 'wwwww55555'
EMAIL_HOST_TLS = False
EMAIL_FROM = 'smokerkiss@sina.com'

MEDIA_URL = '/media/'      #动态文件存储的网页图片链接
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


PAGINATION_SETTINGS = {        #分页
    'PAGE_RANGE_DISPLAYED': 10,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'cache',  # 要缓存的表名
#         'TIMEOUT': 3600,                # 默认的缓存有效时间,以秒计. 默认值是 300 秒(五分钟).
#         'OPTIONS': {
#             'MAX_ENTRIES': 1000        # 缓存的最大条目数(超出该数旧的缓存会被清除,默认值是 300).
#         }
#     }
# }
#
# CACHE_MIDDLEWARE_SECONDS = 500   # 每个页面应该被缓存的秒数

#D:\Python\Python36-32\Lib\site-packages\django\conf
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        #D:\Python\Python36-32\Lib\site-packages\django\core\cache\backends
        'LOCATION':'cache',
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'

