# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='annunciate',
            field=models.CharField(default='', max_length=100, verbose_name='课程通告'),
        ),
    ]
