# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_annunciate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.CharField(default='', max_length=100, verbose_name='视频地址'),
        ),
    ]
